// This file is auto-generated by @hey-api/openapi-ts


export type Body_signin_signin_post = {
    grant_type?: string | null;
    username: string;
    password: string;
    scope?: string;
    client_id?: string | null;
    client_secret?: string | null;
};

export type HTTPValidationError = {
    detail?: Array<ValidationError>;
};

export type User = {
    id?: number | null;
    username: string;
    password_hash: string;
};

export type ValidationError = {
    loc: Array<(string | number)>;
    msg: string;
    type: string;
};

export type $OpenApiTs = {
    '/.well-known/jwks.json': {
        get: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/register': {
        post: {
            req: {
                requestBody: User;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: User;
            };
        };
    };
    '/signin': {
        post: {
            req: {
                formData: Body_signin_signin_post;
            };
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
    '/user': {
        delete: {
            res: {
                /**
                 * Successful Response
                 */
                200: unknown;
            };
        };
    };
};