// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { $OpenApiTs } from './models';

export class DefaultService {
	/**
	 * Get Jwks
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static getJwks(): CancelablePromise<$OpenApiTs['/.well-known/jwks.json']['get']['res'][200]> {
		
		return __request(OpenAPI, {
			method: 'GET',
			url: '/.well-known/jwks.json',
		});
	}

	/**
	 * Register
	 * @returns User Successful Response
	 * @throws ApiError
	 */
	public static register(data: $OpenApiTs['/register']['post']['req']): CancelablePromise<$OpenApiTs['/register']['post']['res'][200]> {
		const {
                    requestBody
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/register',
			body: requestBody,
			mediaType: 'application/json',
			errors: {
				422: `Validation Error`,
			},
		});
	}

	/**
	 * Signin
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static signin(data: $OpenApiTs['/signin']['post']['req']): CancelablePromise<$OpenApiTs['/signin']['post']['res'][200]> {
		const {
                    formData
                } = data;
		return __request(OpenAPI, {
			method: 'POST',
			url: '/signin',
			formData: formData,
			mediaType: 'application/x-www-form-urlencoded',
			errors: {
				422: `Validation Error`,
			},
		});
	}

	/**
	 * Delete User
	 * @returns unknown Successful Response
	 * @throws ApiError
	 */
	public static deleteUser(): CancelablePromise<$OpenApiTs['/user']['delete']['res'][200]> {
		
		return __request(OpenAPI, {
			method: 'DELETE',
			url: '/user',
		});
	}

}